package com.example.store_management.application.service;

import com.example.store_management.application.dto.ProductCreateRequest;
import com.example.store_management.application.dto.ProductPriceChangeRequest;
import com.example.store_management.application.dto.ProductResponse;
import com.example.store_management.domain.model.Product;
import com.example.store_management.domain.model.ProductStatus;
import com.example.store_management.domain.service.PriceChangeHistoryService;
import com.example.store_management.domain.service.ProductService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Application service responsible for orchestrating product-related use cases.
 * It coordinates domain services and performs mapping between DTOs and domain models.
 */
@Service
@RequiredArgsConstructor
public class ProductAppService {

    private final ProductService productService;
    private final PriceChangeHistoryService priceChangeHistoryService;

    /**
     * Creates a new product based on the incoming request and returns a response DTO.
     */
    @Transactional
    public ProductResponse createProduct(ProductCreateRequest request) {
        Product product = mapToDomain(request);
        Product created = productService.createProduct(product);
        return mapToResponse(created);
    }

    /**
     * Returns a product by id as a response DTO.
     */
    @Transactional(readOnly = true)
    public ProductResponse getProductById(UUID id) {
        Product product = productService.getProductById(id);
        return mapToResponse(product);
    }

    /**
     * Changes the price of a product and records the change in price history.
     * This method orchestrates both the product update and the audit in a single transaction.
     */
    @Transactional
    public ProductResponse changePrice(ProductPriceChangeRequest request) {
        // load current state
        Product before = productService.getProductById(request.productId());

        // update price in product
        Product after = productService.changePrice(request.productId(), request.newPrice());

        // record history
        priceChangeHistoryService.recordPriceChange(
                request.productId(),
                before.price(),
                after.price(),
                after.currency(),
                request.changedByUserId(),
                request.reason()
        );

        return mapToResponse(after);
    }

    // ---------- Mapping helpers ----------

    private Product mapToDomain(ProductCreateRequest request) {
        OffsetDateTime now = OffsetDateTime.now();
        return new Product(
                null,                        // id (generated by DB)
                request.sku(),
                request.name(),
                request.description(),
                request.price(),
                request.currency(),
                ProductStatus.ACTIVE,        // default status
                now,
                now
        );
    }

    private ProductResponse mapToResponse(Product product) {
        return new ProductResponse(
                product.id(),
                product.sku(),
                product.name(),
                product.description(),
                product.price(),
                product.currency(),
                product.status().name(),
                product.createdAt(),
                product.updatedAt()
        );
    }
}