package com.example.store_management.application.service;

import com.example.store_management.application.dto.PriceChangeHistoryResponse;
import com.example.store_management.application.dto.ProductCreateRequest;
import com.example.store_management.application.dto.ProductPriceChangeRequest;
import com.example.store_management.application.dto.ProductResponse;
import com.example.store_management.domain.model.PriceChangeHistory;
import com.example.store_management.domain.model.Product;
import com.example.store_management.domain.model.ProductStatus;
import com.example.store_management.domain.service.InventoryService;
import com.example.store_management.domain.service.PriceChangeHistoryService;
import com.example.store_management.domain.service.ProductService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Application service responsible for orchestrating product-related use cases.
 * It coordinates domain services and performs mapping between DTOs and domain models.
 */
@Service
@RequiredArgsConstructor
public class ProductAppService {

    private final ProductService productService;
    private final PriceChangeHistoryService priceChangeHistoryService;
    private final InventoryService inventoryService;

    /**
     * Creates a new product based on the incoming request and returns a response DTO.
     */
    @Transactional
    public ProductResponse createProduct(ProductCreateRequest request) {
        Product product = mapToDomain(request);
        Product created = productService.createProduct(product);

        // create initial inventory with quantity 0
        inventoryService.createInitialInventoryForProduct(created.id());

        return mapToResponse(created);
    }

    /**
     * Returns a product by id as a response DTO.
     */
    @Transactional(readOnly = true)
    public ProductResponse getProductById(UUID id) {
        Product product = productService.getProductById(id);
        return mapToResponse(product);
    }

    /**
     * Returns a list with all the products.
     */
    @Transactional(readOnly = true)
    public List<ProductResponse> listAllProducts() {
        return productService.getAllProducts()
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    /**
     * Changes the price of a product and records the change in price history.
     * This method orchestrates both the product update and the audit in a single transaction.
     */
    @Transactional
    public ProductResponse changePrice(UUID productId, ProductPriceChangeRequest request) {
        // before state
        Product before = productService.getProductById(productId);

        // update price
        Product after = productService.changePrice(productId, request.newPrice());

        // audit
        priceChangeHistoryService.recordPriceChange(
                productId,
                before.price(),
                after.price(),
                after.currency(),
                request.changedByUserId(),
                request.reason()
        );

        return mapToResponse(after);
    }

    /**
     * Returns a list with all the price change history for a product based on the product id.
     * If the product does not exist, a ProductNotFoundException will be thrown.
     */
    @Transactional(readOnly = true)
    public List<PriceChangeHistoryResponse> getPriceHistoryForProduct(UUID productId) {
        // Ensure product exists; will throw ProductNotFoundException (404) if not
        productService.getProductById(productId);

        List<PriceChangeHistory> history = priceChangeHistoryService.getHistoryForProduct(productId);
        return history.stream()
                .map(this::mapToPriceHistoryResponse)
                .toList();
    }

    // ---------- Mapping helpers ----------

    private Product mapToDomain(ProductCreateRequest request) {
        OffsetDateTime now = OffsetDateTime.now();
        return new Product(
                null,                        // id (generated by DB)
                request.sku(),
                request.name(),
                request.description(),
                request.price(),
                request.currency(),
                ProductStatus.ACTIVE,        // default status
                now,
                now
        );
    }

    private ProductResponse mapToResponse(Product product) {
        return new ProductResponse(
                product.id(),
                product.sku(),
                product.name(),
                product.description(),
                product.price(),
                product.currency(),
                product.status().name(),
                product.createdAt(),
                product.updatedAt()
        );
    }

    private PriceChangeHistoryResponse mapToPriceHistoryResponse(PriceChangeHistory history) {
        return new PriceChangeHistoryResponse(
                history.id(),
                history.oldPrice(),
                history.newPrice(),
                history.currency(),
                history.changedByUserId(),
                history.reason(),
                history.changedAt()
        );
    }
}